OSBB_Yovy3/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('support/', admin.site.urls),
    path('', views.home, name='home'),
    path('meters/', include('meters.urls')),
    path('bbq/', include('bbq.urls')),
    path('info/', include('info.urls')),

    # Auth
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

bbq/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = 'bbq'

urlpatterns = [
    path('create/', views.create_booking, name='create_booking'),
    path('my/', views.my_bookings, name='my_bookings'),
    path('all/', views.all_bookings, name='all_bookings'),
    path('future_bookings/', views.future_bookings, name='future_bookings'),
    path('<int:pk>/delete/', views.delete_booking, name='delete_booking'),
    path('success_bbq/', lambda request: render(request, 'bbq/success_bbq.html'), name='success_bbq'),
]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('news/', views.news_list, name='news_list'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('contacts/', views.contact_list, name='contact_list'),
]

meters/urls.py
from django.shortcuts import render
from django.urls import path
from .views import submit_meter_reading, user_meter_readings

app_name = 'meters'

urlpatterns = [
    path('submit/', submit_meter_reading, name='submit_meter_reading'),
    path('success/', lambda request: render(request, 'meters/success.html'), name='meter_success'),
    path('my-readings/', user_meter_readings, name='user_readings')
]

info/models.py
# coding: utf-8

from django.db import models


class News(models.Model):
    title = models.CharField(max_length=200, verbose_name="Назва")
    publication_date = models.DateField(auto_now_add=True, verbose_name="Дата публікації")
    content = models.TextField(verbose_name="Новина")

    def __str__(self):
        return self.title

    def short_content(self):
        return self.content[:100] + "..." if len(self.content) > 100 else self.content

    class Meta:
        verbose_name = "Новина"
        verbose_name_plural = "Новини"


class Contact(models.Model):
    name = models.CharField(max_length=100, verbose_name="Назва")
    phone = models.CharField(max_length=20, verbose_name="Номер телефону")
    comment = models.TextField(blank=True, verbose_name="Додаткова інформація")

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Контакт"
        verbose_name_plural = "Контакти"

info/views.py
from django.shortcuts import get_object_or_404, render

from .models import Contact, News


def news_list(request):
    news_items = News.objects.order_by('-publication_date')
    return render(request, 'info/news_list.html', {'news_items': news_items})


def news_detail(request, pk):
    news_item = get_object_or_404(News, pk=pk)
    return render(request, 'info/news_detail.html', {'news_item': news_item})


def contact_list(request):
    contacts = Contact.objects.all()
    return render(request, 'info/contact_list.html', {'contacts': contacts})

info/templates/info/base.html
{% load static%}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png" href="{% static 'users/images/logo.png' %}">
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

    <style>
        body {
            background-image: url("{% static 'info/images/background.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        .navbar-brand span {
            display: block;
            font-size: 0.9rem;
        }

        .navbar-brand img {
            margin-right: 8px;
        }

        .nav-link {
            margin: 0 5px;
        }

        .container {
            padding-top: 20px;
            padding-bottom: 20px;
        }
    </style>

    <title>ОСББ "АЛЬТА"</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-warning">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
            <img src="{% static 'users/images/logo.png' %}" width="30" height="30" class="d-inline-block align-top">
            <span>ОСББ "АЛЬТА", вул. Віктора Йови, б.3</span>
            {% if user.is_authenticated %}
                <span class="ml-2 text-dark">Квартира {{ user.username }}</span>
            {% endif %}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'meters:submit_meter_reading' %}">Лічильники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bbq:create_booking' %}">Мангал</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:news_list' %}">Новини</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:contact_list' %}">Корисні контакти</a>
                </li>
            </ul>
            {% endif %}
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Вийти</a>
                    <form style="display: none;" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Вийти</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Зареєструватись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Увійти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

info/templates/info/contact_list.html
{% extends "info/base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="col-md-8">
        <h2 class="text-center">Контакти</h2>
            <table class="table table-bordered mt-4">
                <thead class="text-center">
                    <tr>
                        <th>Назва</th>
                        <th>Номер телефону</th>
                        <th>Додаткова інформація</th>
                    </tr>
                </thead>
                <tbody class="text-center">
                    {% for contact in contacts %}
                    <tr>
                        <td>{{ contact.name }}</td>
                        <td>{{ contact.phone }}</td>
                        <td>{{ contact.comment }}</td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
    </div>
</div>
{% endblock %}

info/templates/info/news_detail.html
{% extends "info/base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <div class="container mt-4">
        <h2 class="text-center">{{ news_item.title }}</h2>
        <p>{{ news_item.content }}</p>
        <p><small>Опубліковано: {{ news_item.publication_date }}</small></p>
    </div>
</div>

<div class="row justify-content-center mt-5">
    <a href="{% url 'info:news_list' %}">Назад до списку новин</a>
</div>
{% endblock %}

info/templates/info/news_list.html
{% extends "info/base.html" %}

{% block content %}
<div class="row justify-content-center mt-5">
    <h2 class="text-center">Новини</h2>
</div>
<div class="row justify-content-center mt-3">
    <ul>
    {% for news in news_items %}
        <li>
            <a href="{% url 'info:news_detail' news.pk %}">{{ news.title }}</a>
            <p>{{ news.short_content }}</p>
            <p><small>Опубліковано: {{ news.publication_date }}</small></p>
        </li>
    {% endfor %}
    </ul>
</div>
{% endblock %}