OSBB_Yovy3/urls.py
from django.contrib import admin
from django.urls import path, include
from users import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('support/', admin.site.urls),
    path('', views.home, name='home'),
    path('meters/', include('meters.urls')),
    path('bbq/', include('bbq.urls')),
    path('info/', include('info.urls')),

    # Auth
    path('signup/', views.SignupView.as_view(), name='signup'),
    path('login/', views.UserLoginView.as_view(), name='login'),
    path('logout/', views.UserLogoutView.as_view(), name='logout'),

    # Password reset
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'),
         name='password_reset'),
    path('password_reset/done/',
         auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('reset/done/',
         auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

bbq/urls.py
from django.shortcuts import render
from django.urls import path

from . import views

app_name = 'bbq'

urlpatterns = [
    path('create/', views.create_booking, name='create_booking'),
    path('my/', views.my_bookings, name='my_bookings'),
    path('all/', views.all_bookings, name='all_bookings'),
    path('future_bookings/', views.future_bookings, name='future_bookings'),
    path('<int:pk>/delete/', views.delete_booking, name='delete_booking'),
    path('success_bbq/', lambda request: render(request, 'bbq/success_bbq.html'), name='success_bbq'),
]

info/urls.py
from django.urls import path
from . import views

app_name = 'info'

urlpatterns = [
    path('news/', views.news_list, name='news_list'),
    path('news/<int:pk>/', views.news_detail, name='news_detail'),
    path('contacts/', views.contact_list, name='contact_list'),
]

meters/urls.py
from django.shortcuts import render
from django.urls import path
from .views import submit_meter_reading, user_meter_readings

app_name = 'meters'

urlpatterns = [
    path('submit/', submit_meter_reading, name='submit_meter_reading'),
    path('success/', lambda request: render(request, 'meters/success.html'), name='meter_success'),
    path('my-readings/', user_meter_readings, name='user_readings')
]

meters/models.py
# coding: utf-8

from django.db import models
from users.models import User


class MeterReading(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='meter_readings')
    cold_water_1 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Холодна вода 1')
    cold_water_2 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Холодна вода 2')
    hot_water_1 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Гаряча вода 1')
    hot_water_2 = models.PositiveIntegerField(null=True, blank=True, verbose_name='Гаряча вода 2')
    submission_date = models.DateTimeField(auto_now_add=True, verbose_name='Дата подання')

    class Meta:
        verbose_name = "Лічильник"
        verbose_name_plural = "Лічильники"

    def __str__(self):
        return f"Показання від {self.user} ({self.submission_date})"

meters/forms.py
# coding: utf-8

from django import forms
from .models import MeterReading


class MeterReadingForm(forms.ModelForm):
    class Meta:
        model = MeterReading
        fields = ['cold_water_1', 'cold_water_2', 'hot_water_1', 'hot_water_2']
        widgets = {
            'cold_water_1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Показник лічильника холодної води 1'}),
            'cold_water_2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Показник лічильника холодної води 2'}),
            'hot_water_1': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Показник лічильника гарячої води 1'}),
            'hot_water_2': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Показник лічильника гарячої води 2'}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop('user', None)
        super().__init__(*args, **kwargs)

        # Настраиваем отображение полей в зависимости от группы пользователя
        if user and user.group == 'group1':
            self.fields['cold_water_2'].widget = forms.HiddenInput()
            self.fields['hot_water_2'].widget = forms.HiddenInput()

    def clean(self):
        cleaned_data = super().clean()
        cold_water_1 = cleaned_data.get("cold_water_1")
        hot_water_1 = cleaned_data.get("hot_water_1")

        # Проверяем, что обязательные поля заполнены
        if cold_water_1 is None:
            self.add_error('cold_water_1', 'Це поле обов’язкове.')
        if hot_water_1 is None:
            self.add_error('hot_water_1', 'Це поле обов’язкове.')

        return cleaned_data

meters/views.py
# coding: utf-8

from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from .forms import MeterReadingForm
from .models import MeterReading


@login_required
def submit_meter_reading(request):
    if request.method == 'POST':
        form = MeterReadingForm(request.POST, user=request.user)
        if form.is_valid():
            meter_reading = form.save(commit=False)
            meter_reading.user = request.user
            meter_reading.save()
            return redirect('meters:meter_success')
    else:
        form = MeterReadingForm(user=request.user)
    return render(request, 'meters/submit_reading.html', {'form': form})


@login_required
def user_meter_readings(request):
    user = request.user
    readings = MeterReading.objects.filter(user=user).order_by('-submission_date')
    context = {
        'readings': readings,
        'is_group1': user.group == 'group1',  # Проверка группы
    }
    return render(request, 'meters/user_readings.html', context)

meters/templates/meters/base.html
{% load static%}

<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <link rel="icon" type="image/png" href="{% static 'users/images/logo.png' %}">
    <link rel="stylesheet" href="{% static 'users/css/styles.css' %}">

    <style>
        body {
            background-image: url("{% static 'meters/images/background.jpg' %}");
            background-size: cover;
            background-repeat: no-repeat;
            background-position: center;
        }

        .navbar-brand span {
            display: block;
            font-size: 0.9rem;
        }

        .navbar-brand img {
            margin-right: 8px;
        }

        .nav-link {
            margin: 0 5px;
        }

        .container {
            padding-top: 20px;
            padding-bottom: 20px;
        }
    </style>

    <title>ОСББ "АЛЬТА"</title>
</head>
<body>

<nav class="navbar navbar-expand-md navbar-light bg-warning">
    <div class="container">
        <a class="navbar-brand d-flex align-items-center" href="{% url 'home' %}">
            <img src="{% static 'users/images/logo.png' %}" width="30" height="30" class="d-inline-block align-top">
            <span>ОСББ "АЛЬТА", вул. Віктора Йови, б.3</span>
            {% if user.is_authenticated %}
                <span class="ml-2 text-dark">Квартира {{ user.username }}</span>
            {% endif %}
        </a>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarNav">
            {% if user.is_authenticated %}
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'meters:submit_meter_reading' %}">Лічильники</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'bbq:create_booking' %}">Мангал</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:news_list' %}">Новини</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'info:contact_list' %}">Корисні контакти</a>
                </li>
            </ul>
            {% endif %}
            <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="#" onclick="$('#signOutBtn').click()" class="nav-link">Вийти</a>
                    <form style="display: none;" method="POST" action="{% url 'logout' %}">
                        {% csrf_token %}
                        <button id="signOutBtn" type="submit">Вийти</button>
                    </form>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'signup' %}">Зареєструватись</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">Увійти</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    {% block content %}{% endblock %}
</div>

<!-- Optional JavaScript -->
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

meters/templates/meters/submit_reading.html
{% extends "users/base.html" %}

{% block content %}
<div class="row justify-content-center mt-3">
    <div class="col-md-6">
        <a href="{% url 'meters:user_readings' %}" class="btn btn-primary btn-block">Подивитись мої показники</a>
        <br>
        <h2 class="text-center">Передача показників лічильників</h2>
        <form method="POST">
            {% csrf_token %}
            {% for field in form %}
                <div class="form-group">
                    <label for="{{ field.id_for_label }}">{{ field.label }}</label>
                    {{ field }}
                    {% if field.errors %}
                        <div class="invalid-feedback d-block">
                            {{ field.errors|striptags }}
                        </div>
                    {% endif %}
                </div>
            {% endfor %}
            <button type="submit" class="btn btn-primary btn-block">Передати показники</button>
        </form>
    </div>
</div>
{% endblock %}

meters/templates/meters/success.html
{% extends "users/base.html" %}

{% block content %}
<div class="text-center mt-5">
    <h2>Дякуємо за показники!</h2>
    <p>Ваші дані успішно збережені.</p>
    <a href="{% url 'meters:user_readings' %}" class="btn btn-primary">Подивитись передані показники</a>
</div>
{% endblock %}

meters/templates/meters/user_readings.html
{% extends "users/base.html" %}

{% block content %}
<div class="container mt-5">
    <h2 class="text-center">Ваші показники</h2>
    <table class="table table-bordered mt-4">
        <thead>
            <tr>
                <th>Дата подання</th>
                <th>Холодна вода 1</th>
                {% if not is_group1 %}
                <th>Холодна вода 2</th>
                {% endif %}
                <th>Гаряча вода 1</th>
                {% if not is_group1 %}
                <th>Гаряча вода 2</th>
                {% endif %}
            </tr>
        </thead>
        <tbody>
            {% for reading in readings %}
                <tr>
                    <td>{{ reading.submission_date }}</td>
                    <td>{{ reading.cold_water_1 }}</td>
                    {% if not is_group1 %}
                    <td>{{ reading.cold_water_2 }}</td>
                    {% endif %}
                     <td>{{ reading.hot_water_1 }}</td>
                    {% if not is_group1 %}
                    <td>{{ reading.hot_water_2 }}</td>
                    {% endif %}
                </tr>
            {% empty %}
                <tr>
                    <td colspan="5" class="text-center">Ще немає переданих показників</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}